name: uhf_rfid_plugin
description: "Flutter plugin for UHF RFID R2000 SDK and Barcode/QR Scanner. Supports PDA7100, PDA3109 and similar handheld devices."
version: 1.0.0
homepage: https://github.com/necro304/uhf_rfid_plugin
repository: https://github.com/necro304/uhf_rfid_plugin
issue_tracker: https://github.com/necro304/uhf_rfid_plugin/issues

topics:
  - rfid
  - uhf
  - barcode
  - scanner
  - pda

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  plugin_platform_interface: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.uhf_rfid_plugin
        pluginClass: UhfRfidPlugin
